# Default values for centNodeChart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nodes: 'https://35.184.66.29:8082,https://35.184.39.100:8082'

network: 'russianhill'

namespace: default

rinkeby:
  contractAddresses:
    paymentObligation: "0x691280677b52e3ca71e023eed2d83fa9fac3b64b"

kovan:
  contractAddresses:
    paymentObligation: "0xa3d3b45f422016201d7cd4c2bc217665483d90e6"


